import { Head, Link, usePage } from '@inertiajs/react';

type Listing = { id: number; title: string; listed_by_role: string; rent_amount: string; city: string; area: string; listing_status: string; verification_status: string; expires_at: string; owner_name?: string };

export default function MyListings() {
    const { listings } = usePage<{ listings: { data: Listing[]; total: number } }>().props;

    return <><Head title="My Listings" /><main className="min-h-screen bg-slate-50 px-4 py-6 text-slate-950 sm:px-8"><div className="mx-auto max-w-4xl"><div className="flex items-center justify-between"><Link href="/" className="font-black text-blue-700">RoomConnect</Link><Link href="/post-room" className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-bold text-white">Post a room</Link></div><div className="mt-10"><p className="text-sm font-semibold text-blue-700">Your activity</p><h1 className="mt-2 text-3xl font-black">My listings</h1><p className="mt-2 text-slate-500">Aapne jo rooms list kiye hain unka status yahan track karein.</p></div><div className="mt-6 space-y-4">{listings.data.map((listing) => <article key={listing.id} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold capitalize text-slate-600">Listed by {listing.listed_by_role}</span><h2 className="mt-3 text-lg font-bold">{listing.title}</h2><p className="mt-1 text-sm text-slate-500">{listing.area}, {listing.city} · ₹{Number(listing.rent_amount).toLocaleString('en-IN')}/mo</p></div><div className="flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-emerald-50 px-3 py-1 text-emerald-700">{listing.listing_status}</span><span className="rounded-full bg-amber-50 px-3 py-1 text-amber-700">{listing.verification_status}</span></div></div><div className="mt-4 border-t border-slate-100 pt-4 text-xs text-slate-500">Owner: {listing.owner_name || 'Added securely'} · Expires: {listing.expires_at}</div></article>)}{!listings.data.length && <div className="rounded-3xl border border-dashed border-slate-300 bg-white p-8 text-center text-slate-500">Abhi koi listing nahi hai.</div>}</div></div></main></>;
}
