import { Head, Link, usePage } from '@inertiajs/react';

type Metrics = { total_users: number; active_listings: number; open_reports: number; today_unlocks: number; verified_donations: string };

export default function Dashboard() {
    const { metrics, error } = usePage<{ metrics: Metrics | null; error?: string }>().props;
    const cards = metrics ? [['Users', metrics.total_users], ['Active listings', metrics.active_listings], ['Open reports', metrics.open_reports], ['Today unlocks', metrics.today_unlocks], ['Verified donations', `₹${Number(metrics.verified_donations).toLocaleString('en-IN')}`]] : [];
    return <><Head title="Admin Dashboard" /><main className="min-h-screen bg-slate-50 px-4 py-6 text-slate-950 sm:px-8"><div className="mx-auto max-w-5xl"><div className="flex items-center justify-between"><Link href="/" className="font-black text-blue-700">RoomConnect Admin</Link><Link href="/admin/activity-logs" className="text-sm font-semibold text-slate-600">Audit logs</Link></div><h1 className="mt-10 text-3xl font-black">Admin dashboard</h1><p className="mt-2 text-slate-500">Platform health aur moderation overview.</p>{error && <div className="mt-6 rounded-2xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}<div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{cards.map(([label, value]) => <div key={String(label)} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-black text-slate-900">{value}</p></div>)}</div><div className="mt-8 grid gap-4 sm:grid-cols-2"><Link href="/admin/moderation" className="rounded-3xl bg-red-600 p-6 text-white shadow-sm"><p className="text-sm font-semibold text-red-100">Trust & safety</p><h2 className="mt-2 text-xl font-black">Open moderation</h2><p className="mt-2 text-sm text-red-100">Reported listings review karein.</p></Link><Link href="/admin/activity-logs" className="rounded-3xl bg-slate-900 p-6 text-white shadow-sm"><p className="text-sm font-semibold text-slate-300">Security</p><h2 className="mt-2 text-xl font-black">Activity and audit logs</h2><p className="mt-2 text-sm text-slate-300">Admin actions trace karein.</p></Link></div></div></main></>;
}
