import { Head, Link, router, usePage } from '@inertiajs/react';

type Report = { id: number; reason: string; details?: string; status: string; moderation_action: string; post: { title: string; slug: string; listing_status: string; is_flagged: boolean }; user?: { name: string; email: string } };

export default function Moderation() {
    const { reports } = usePage<{ reports: { data: Report[]; total: number } }>().props;
    function update(id: number, status: string, moderation_action: string) { router.patch(`/admin/moderation/${id}`, { status, moderation_action }, { preserveScroll: true }); }
    return <><Head title="Listing Moderation" /><main className="min-h-screen bg-slate-50 px-4 py-6 text-slate-950 sm:px-8"><div className="mx-auto max-w-5xl"><div className="flex items-center justify-between"><Link href="/" className="font-black text-blue-700">RoomConnect Admin</Link><span className="rounded-full bg-red-50 px-3 py-1 text-xs font-bold text-red-700">Moderation</span></div><h1 className="mt-10 text-3xl font-black">Listing moderation</h1><p className="mt-2 text-slate-500">Reports review karein aur suspicious listing ko hide/restore karein.</p><div className="mt-6 space-y-4">{reports.data.map((report) => <article key={report.id} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><span className="rounded-full bg-red-50 px-2.5 py-1 text-xs font-bold uppercase text-red-700">{report.reason.replaceAll('_', ' ')}</span><h2 className="mt-3 text-lg font-bold">{report.post.title}</h2><p className="mt-1 text-sm text-slate-500">Reported by {report.user?.name ?? 'User'} · {report.post.listing_status}</p></div><span className="h-fit rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold">{report.status}</span></div>{report.details && <p className="mt-4 rounded-xl bg-slate-50 p-3 text-sm text-slate-600">{report.details}</p>}<div className="mt-5 flex flex-wrap gap-2"><button onClick={() => update(report.id, 'reviewing', 'none')} className="rounded-xl border border-slate-200 px-3 py-2 text-sm font-bold">Review</button><button onClick={() => update(report.id, 'resolved', 'hide')} className="rounded-xl bg-red-600 px-3 py-2 text-sm font-bold text-white">Hide listing</button><button onClick={() => update(report.id, 'dismissed', 'restore')} className="rounded-xl bg-emerald-600 px-3 py-2 text-sm font-bold text-white">Dismiss / restore</button></div></article>)}{!reports.data.length && <div className="rounded-3xl border border-dashed border-slate-300 bg-white p-8 text-center text-slate-500">No reports pending.</div>}</div></div></main></>;
}
